Repository CartoDB/carto-vl, pull requests merged in 2018-07, with the labels that each got.

#540 Update of the contribution information
  CONTRIBUTING.md
  README.md
Labels: documentation

#678 Bugfix for blending to variables multiple times
  debug/list.html
  src/renderer/viz/expressions/basic/variable.js
  test/integration/user/test/expressions.test.js
  test/integration/user/test/interactivity.test.js
  test/integration/user/test/layer.test.js
  test/integration/user/test/viewportFeatures.test.js
Labels: bug

#722 Fix animation
  examples/interactivity/animation-controls.html
  src/client/windshaft.js
Labels: bug

#723 Fix interactivity points
  src/renderer/Dataframe.js
  test/unit/renderer/dataframe.test.js
Labels: bug

#753 Cache imagePixels in ramp
  src/renderer/viz/expressions/ramp.js
Labels: 💫 Performance

#763 Modified image examples
  examples/styling/image-external.html
  examples/styling/image-multiple.html
  examples/styling/image-single.html
Labels: 🖼️ Examples

#766 Workaround core-js performance bug
  src/renderer/Renderer.js
  src/renderer/decoder.js
  src/utils/util.js
Labels: 💫 Performance

#758 Add hide / show layer methods
  debug/layer-visibility.html
  src/Layer.js
  src/constants/layer.js
  src/integrator/Map.js
  src/integrator/mapbox-gl.js
  test/integration/user/test/interactivity.test.js
  test/integration/user/test/layer.test.js
Labels: 🙋feature-request

#749 Optimizations
  src/Viz.js
  src/renderer/Dataframe.js
  src/renderer/Metadata.js
  src/renderer/decoder.js
  src/renderer/viz/expressions/color/NamedColor.js
  src/sources/MVT.js
  test/unit/renderer/dataframe.test.js
  test/unit/renderer/viz/expressions/ramp.test.js
Labels: 💫 Performance

#773 Improve GeoJSON source
  src/sources/GeoJSON.js
  test/common/sources/multi-polygon-reverse.geojson
  test/integration/render/scenarios/geometries/multi-polygon/reverse/reference.png
  test/integration/render/scenarios/geometries/multi-polygon/reverse/scenario.js
  test/unit/source/GeoJSON.test.js
Labels: ✨ Enhancement

#768 Fix viewport expressions
  src/client/windshaft-filtering.js
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterAggregation.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterAvg.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterMax.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterMin.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterMode.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterSum.js
  src/renderer/viz/expressions/aggregation/clusterAggregation.js
  src/renderer/viz/expressions/aggregation/global/GlobalAggregation.js
  src/renderer/viz/expressions/aggregation/global/GlobalAvg.js
  src/renderer/viz/expressions/aggregation/global/GlobalCount.js
  src/renderer/viz/expressions/aggregation/global/GlobalMax.js
  src/renderer/viz/expressions/aggregation/global/GlobalMin.js
  src/renderer/viz/expressions/aggregation/global/GlobalPercentile.js
  src/renderer/viz/expressions/aggregation/global/GlobalSum.js
  src/renderer/viz/expressions/aggregation/globalAggregation.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportAggregation.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportAvg.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportCount.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportHistogram.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportMax.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportMin.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportPercentile.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportSum.js
  src/renderer/viz/expressions/aggregation/viewportAggregation.js
  src/renderer/viz/expressions/base.js
  src/renderer/viz/expressions/classification/Classifier.js
  src/renderer/viz/expressions/classification/GlobalEqIntervals.js
  src/renderer/viz/expressions/classification/GlobalQuantiles.js
  src/renderer/viz/expressions/classification/ViewportEqIntervals.js
  src/renderer/viz/expressions/classification/ViewportQuantiles.js
  src/renderer/viz/expressions/classifier.js
  src/renderer/viz/expressions/ramp.js
  src/renderer/viz/expressions/utils.js
  test/common/sources/many-points.geojson
  test/integration/render/scenarios/classification/viewportEqIntervals/reference.png
  test/integration/render/scenarios/classification/viewportEqIntervals/scenario.js
  test/integration/render/scenarios/classification/viewportEqIntervalsExpression/reference.png
  test/integration/render/scenarios/classification/viewportEqIntervalsExpression/scenario.js
  test/integration/render/scenarios/classification/viewportQuantilesExpression/reference.png
  test/integration/render/scenarios/classification/viewportQuantilesExpression/scenario.js
  test/unit/renderer/viz/expressions/aggregation/viewportAggregation.test.js
  test/unit/renderer/viz/expressions/classifier.test.js
  test/unit/renderer/viz/expressions/linear.test.js
  test/unit/renderer/viz/expressions/utils.js
Labels: 🔀 Expressions

#597 Add performance testing infrastructure
  package.json
  test/benchmark/.eslintrc.json
  test/benchmark/fps/benchmark.html
  test/benchmark/fps/benchmark.js
  test/benchmark/index.test.js
  test/benchmark/karma.conf.js
  test/benchmark/perf.spec.js
  yarn.lock
Labels: 💫 Performance, 😊 Dev Happiness

#790 Ignore skipped tests in the output
  test/integration/user/karma.conf.js
  test/unit/karma.conf.js
Labels: 😊 Dev Happiness
