Repository CartoDB/carto-vl, pull requests merged in 2018-11, with the labels that each got.

#1113 Fix animations
  debug/timerange.html
  examples/guides/ramp/accidents-all.html
  src/renderer/viz/expressions/Animation.js
  src/renderer/viz/expressions/AnimationGeneral.js
  src/renderer/viz/expressions/AnimationRange.js
  src/renderer/viz/expressions/Variant.js
  src/renderer/viz/expressions/base.js
  test/unit/renderer/viz/expressions/Animation.test.js
  test/unit/renderer/viz/expressions/utils.js
Labels: 🐛Bug

#1117 Fix `/examples/advanced/taxi-pickups.html`
  src/renderer/viz/expressions/AnimationGeneral.js
Labels: 🐛Bug

#1137 Change example for animated-viz guide so it allows 0 duration
  examples/guides/animated-viz/step-5.html
Labels: 🐛Bug

#1155 Add timestamp to animation controls example
  examples/interactivity/animation-controls.html
Labels: ✨ Enhancement, 🖼️ Examples

#1156 rm beta version sentence
  README.md
Labels: 📖 Documentation

#1154 Add codec conversion to eval in linear
  CHANGELOG.md
  debug/viewportfeatures-perf.html
  src/renderer/viz/expressions/linear.js
  test/unit/renderer/viz/expressions/linear.test.js
Labels: 🐛Bug, 🔀 Expressions

#1158 Review Renderer + Layer refactor
  src/Layer.js
  src/LayerConcurrencyHelper.js
  src/interactivity/Interactivity.js
  src/interactivity/feature.js
  src/renderer/Dataframe.js
  src/renderer/Renderer.js
  src/renderer/shaders/geometry/line/lineVertexShader.glsl
  src/renderer/shaders/geometry/point/pointFragmentShader.glsl
  src/renderer/shaders/geometry/point/pointVertexShader.glsl
  src/renderer/shaders/symbolizer/symbolizerVertexShader.glsl
  src/renderer/viz/expressions/aggregation/global/GlobalAvg.js
  test/unit/LayerConcurrencyHelper.test.js
Labels: ✨ Enhancement, 😊 Dev Happiness

#1163 Fix transparent color
  CHANGELOG.md
  debug/image-external-no-color.html
  src/Viz.js
  src/renderer/shaders/symbolizer/symbolizerFragmentShader.glsl
  src/renderer/shaders/symbolizer/symbolizerVertexShader.glsl
  src/renderer/viz/expressions/color/NamedColor.js
  test/integration/render/scenarios/color/transparent/reference.png
  test/integration/render/scenarios/color/transparent/scenario.js
  test/unit/renderer/viz/expressions/color/NamedColor.test.js
Labels: 🐛Bug

#1167 Fix viewportQuantiles
  CHANGELOG.md
  src/Viz.js
  src/renderer/viz/expressions/classification/Classifier.js
  src/renderer/viz/expressions/classification/ViewportQuantiles.js
  src/renderer/viz/expressions/classification/ViewportStandardDev.js
  test/unit/renderer/viz/expressions/classification/classifier.test.js
Labels: 🐛Bug, 🔀 Expressions

#1168 Store config objects instead of encoded ones
  examples/editor/index.js
Labels: ✏️ Editor, ✨ Enhancement, 😊 Dev Happiness

#1169 Examples in editor using `cartovl` user
  examples/editor/examples.js
  examples/editor/index.html
  examples/editor/index.js
Labels: ✏️ Editor, 😊 Dev Happiness
