Repository CartoDB/carto-vl, pull requests merged in 2018-08, with the labels that each got.

#792 Fix GeoJSON category to ID
  src/sources/GeoJSON.js
  test/common/sources/points2.geojson
  test/integration/render/scenarios/regression/multiple-categories/reference.png
  test/integration/render/scenarios/regression/multiple-categories/scenario.js
Labels: 🐛Bug

#801 Remove breaking Uglify plugin from minified build
  package.json
  webpack/webpack.min.config.js
Labels: 🐛Bug

#806 Document MVT metadata object
  src/sources/MVT.js
Labels: 📖 Documentation

#799 Decode optimization
  src/renderer/Renderer.js
  src/renderer/decoder/common.js
  src/renderer/decoder/lineDecoder.js
  src/renderer/decoder/polygonDecoder.js
  src/utils/geometry.js
  src/utils/util.js
  test/benchmark/performance/decoder/line.spec.js
  test/benchmark/performance/decoder/point.spec.js
  test/benchmark/performance/decoder/polygon.spec.js
Labels: 💫 Performance

#824 Document MVT templateURLs correctly
  src/sources/MVT.js
Labels: 📖 Documentation

#837 Use local MGL files for testing
  test/benchmark/fps/benchmark.html
  test/integration/render/render.html.tpl
Labels: 😊 Dev Happiness

#777 Fix ramp animated values
  src/renderer/viz/expressions/base.js
  src/renderer/viz/expressions/basic/array.js
  src/renderer/viz/expressions/now.js
  src/renderer/viz/expressions/ramp.js
  test/unit/renderer/viz/expressions/ramp.test.js
Labels: 🐛Bug

#852 Minor perf improvements
  CHANGELOG.md
  src/client/windshaft.js
  src/renderer/Dataframe.js
Labels: 💫 Performance

#861 Increase test timeouts
  package.json
Labels: tests, 😊 Dev Happiness

#866 Fix example
  examples/interactivity/enter-leave.html
Labels: 🐛Bug, 🖼️ Examples

#874 Rename old legacy "tile" names
  src/renderer/Dataframe.js
  src/renderer/Renderer.js
Labels: 😊 Dev Happiness

#851 Fix ramp for categories
  CHANGELOG.md
  src/client/windshaft.js
  src/renderer/Metadata.js
  src/renderer/viz/expressions/basic/property.js
  src/renderer/viz/expressions/ramp.js
  src/sources/GeoJSON.js
  src/sources/MVT.js
Labels: 🙅 do-not-merge

#882 Fix opacity() with variables
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/color/Opacity.js
  test/unit/renderer/viz/expressions/color/Opacity.test.js
Labels: 🐛Bug

#876 Check second param for buckets() is an array
  CHANGELOG.md
  src/renderer/viz/expressions/buckets.js
  test/unit/renderer/viz/expressions/buckets.test.js
Labels: ✨ Enhancement, 🔀 Expressions

#873 Generic reverse
  CHANGELOG.md
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/basic/array.js
  src/renderer/viz/expressions/reverse/ReverseArray.js
  src/renderer/viz/expressions/reverse/ReversePalette.js
  src/renderer/viz/expressions/reverse/reverse.js
  test/integration/render/scenarios/ramp/reverse-cartocolor/reference.png
  test/integration/render/scenarios/ramp/reverse-cartocolor/scenario.js
  test/integration/render/scenarios/ramp/reverse-custompalette/reference.png
  test/integration/render/scenarios/ramp/reverse-custompalette/scenario.js
  test/unit/renderer/viz/expressions/reverse/reverse.test.js
Labels: ✨ Enhancement, 🔀 Expressions

#896 Add clusterCount expression
  CHANGELOG.md
  src/client/windshaft.js
  src/renderer/schema.js
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterCount.js
  src/sources/MVT.js
  test/unit/renderer/viz/expressions/aggregation/clusterAggregation.test.js
Labels: 🔀 Expressions, 🙋feature-request

#911 Rename Dataframe.bind()
  src/renderer/Dataframe.js
  src/renderer/RenderLayer.js
Labels: 😊 Dev Happiness
