Repository CartoDB/carto-vl, pull requests merged in 2018-05, with the labels that each got.

#401 Update MGL to v0.45.0
  docs/README.md
  examples/basics/change-source.html
  examples/basics/change-style.html
  examples/basics/multi-layer.html
  examples/basics/single-layer.html
  examples/editor/index.html
  examples/expressions/animation.html
  examples/expressions/bubblemap.html
  examples/expressions/color.html
  examples/expressions/default.html
  examples/expressions/filter.html
  examples/expressions/histogram.html
  examples/expressions/order.html
  examples/expressions/ramp-category.html
  examples/expressions/ramp-numeric.html
  examples/expressions/torque.html
  examples/expressions/viewport.html
  examples/interactivity/feature-click.html
  examples/interactivity/feature-enter-leave.html
  examples/interactivity/feature-hover.html
  examples/interactivity/multi-feature.html
  examples/interactivity/style-feature.html
  examples/misc/boilerplate.html
  examples/misc/edit-sql-expressions.html
  examples/misc/geojson-viewer.html
  examples/misc/populated-places.html
  examples/misc/popups.html
  package.json
  test/benchmark/benchmark.html
  yarn.lock
Labels: mapbox-gl

#445 362 beta guides
  docs/guides/01-getting-started.md
  docs/guides/01-quickstart.md
  docs/guides/02-syntax.md
  docs/guides/03-expressions.md
  docs/guides/04-interpolation.md
  docs/guides/05-interactivity.md
  docs/guides/0X-styling-polygons
  docs/guides/0X2-styling-points
  docs/guides/0X3-styling-lines
  docs/guides/0X4-styling-polygons
  examples/guides/getting-started/addingData.html
  examples/guides/getting-started/basemap.html
  examples/guides/getting-started/basicStyling.html
  examples/guides/interactivity/featureEnter.html
  examples/guides/interactivity/popups.html
  examples/guides/interactivity/variables.html
  examples/guides/interpolation/step-0.html
  examples/guides/interpolation/step-1.html
  examples/guides/interpolation/step-2.html
Labels: documentation, guides

#481 Minor performance improvement
  src/core/shaders/geometry/line-glsl.js
  src/core/shaders/geometry/point-glsl.js
  src/core/shaders/geometry/triangle-glsl.js
  test/benchmark/benchmark.html
  test/benchmark/benchmark.js
Labels: performance
