Repository CartoDB/carto-vl, pull requests merged in 2018-09, with the labels that each got.

#913 Add CORS documentation
  docs/guides/08-introduction-to-image-files.md
Labels: 📖 Documentation

#918 Improve ordering docs
  src/renderer/viz/expressions/ordering.js
Labels: 📖 Documentation

#916 Fix animation integration with MGL
  src/Layer.js
  src/maps/Map.js
Labels: 🐛Bug

#942 Optimize viewport aggs.
  src/renderer/Dataframe.js
  src/renderer/Renderer.js
Labels: 💫 Performance

#909 Add support for Mean Standard Deviation classification method
  CHANGELOG.md
  examples/styling/style-by-number.html
  package.json
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/classification/Classifier.js
  src/renderer/viz/expressions/classification/GlobalQuantiles.js
  src/renderer/viz/expressions/classification/GlobalStandardDev.js
  src/renderer/viz/expressions/classification/ViewportStandardDev.js
  src/renderer/viz/expressions/stats.js
  test/integration/render/scenarios/classification/globalStandardDev/reference.png
  test/integration/render/scenarios/classification/globalStandardDev/scenario.js
  test/integration/render/scenarios/classification/viewportStandardDev/reference.png
  test/integration/render/scenarios/classification/viewportStandardDev/scenario.js
  test/integration/render/scenarios/classification/viewportStandardDevExpression/reference.png
  test/integration/render/scenarios/classification/viewportStandardDevExpression/scenario.js
  test/unit/renderer/viz/expressions/classification/classifier.test.js
  test/unit/renderer/viz/expressions/stats.test.js
Labels: 🔀 Expressions, 🗂️ Classification

#964 Fix windshaft-filtering
  src/client/windshaft-filtering.js
Labels: 🐛Bug

#968 Add support for `opacity()` with images as first parameter
  CHANGELOG.md
  src/renderer/viz/expressions/color/Opacity.js
  test/unit/renderer/viz/expressions/color/Opacity.test.js
  test/unit/renderer/viz/expressions/utils.js
Labels: ✨ Enhancement

#972 Fix filtered image
  src/renderer/shaders/symbolizer/symbolizerFragmentShader.glsl
  src/renderer/shaders/symbolizer/symbolizerVertexShader.glsl
  test/integration/render/scenarios/regression/filtered-image/reference.png
  test/integration/render/scenarios/regression/filtered-image/scenario.js
Labels: 🐛Bug
