Repository CartoDB/carto-vl, pull requests merged in 2018-06, with the labels that each got.

#504 Fix ethnic example
  src/core/viz/expressions/binary.js
  test/unit/core/viz/expressions/color/opacity.test.js
Labels: bug

#505 animation guide with examples
  docs/guides/06-introduction-to-animation.md
  docs/guides/07-introduction-to-interactivity.md
  examples/guides/animation/step-1.html
  examples/guides/animation/step-2.html
  examples/guides/animation/step-3.html
  examples/guides/animation/step-4.html
Labels: guides

#542 Fix E2E tests
  test/acceptance/e2e.html.tpl
  test/acceptance/e2e.test.js
  test/acceptance/e2e/sf_stclines/reference.png
  test/common/util.js
  test/integration/render/render.test.js
  test/integration/render/scenarios/sprites/ramp/scenario.js
  test/integration/render/scenarios/sprites/single/scenario.js
Labels: bug

#549 Fix change animation duration
  src/core/viz/expressions/torque.js
  test/unit/core/viz/expressions/torque.test.js
Labels: bug

#566 Document Layer.update()
  src/api/layer.js
Labels: documentation

#563 Replace var by const
  .eslintrc.json
  examples/editor/index.js
  scripts/cdn/invalidate.js
  scripts/cdn/publish.js
  src/api/error-handling/carto-error.js
  src/api/integrator/mapbox-gl.js
  src/api/source/base-windshaft.js
  src/api/source/geojson.js
  src/api/source/sql.js
  src/client/windshaft.js
  src/core/renderer.js
  src/core/viz/parser.js
  test/integration/user/api/interactivity.test.js
  test/integration/user/api/layer.test.js
  test/integration/user/index.test.js
  test/unit/index.test.js
  webpack/banner.js
Labels: dev-happiness
