Repository CartoDB/carto-vl, pull requests merged in 2018-10, with the labels that each got.

#1008 Scaled fix
  src/renderer/viz/expressions/Scaled.js
  test/unit/renderer/viz/expressions/Scaled.test.js
Labels: 🐛Bug

#1010 Fix ramp others
  src/renderer/viz/expressions/Ramp.js
  src/renderer/viz/expressions/RampGeneric.js
  test/unit/renderer/viz/expressions/ramp.test.js
Labels: 🐛Bug

#1015 Fix request tiles & Fix interactivity corner case & Fix perf regression
  debug/viewportAggPluto.html
  src/Layer.js
  src/renderer/Dataframe.js
Labels: 🐛Bug

#1021 Add glossary
  docs/guides/0x-glossary.md
Labels: 📖 Documentation

#1027 Deal with failing basemaps render tests
  test/integration/render/scenarios/basemaps/darkmatter/reference.png
  test/integration/render/scenarios/basemaps/darkmatter/scenario.js
  test/integration/render/scenarios/basemaps/positron/reference.png
  test/integration/render/scenarios/basemaps/positron/scenario.js
  test/integration/render/scenarios/basemaps/voyager/reference.png
  test/integration/render/scenarios/basemaps/voyager/scenario.js
Labels: tests, 😊 Dev Happiness

#1040 Fix master
  docs/guides/Glossary.md
  examples/guides/animation/step-1.html
  examples/guides/animation/step-2.html
  examples/guides/animation/step-3.html
  examples/guides/animation/step-4.html
  examples/guides/getting-started/step-1.html
  examples/guides/getting-started/step-2.html
  examples/guides/image-files/align-image.html
  examples/guides/image-files/built-in-image.html
  examples/guides/image-files/category-to-image.html
  examples/guides/image-files/color-category-image.html
  examples/guides/image-files/color-image.html
  examples/guides/image-files/external-image.html
  examples/guides/interactivity/featureEnter.html
  examples/guides/interactivity/popups.html
  examples/guides/interactivity/step-1.html
  examples/guides/interactivity/step-2.html
  examples/guides/interactivity/step-3.html
  examples/guides/interactivity/step-4.html
  examples/guides/interactivity/variables.html
  examples/guides/interpolation/step-0.html
  examples/guides/interpolation/step-1.html
  examples/guides/interpolation/step-2.html
  examples/guides/sources/step-1.html
  examples/guides/sources/step-2.html
  examples/guides/sources/step-3.html
  examples/interactivity/enter-leave.html
  examples/misc/edit-sql-expressions.html
  examples/misc/legends/legend-categorical-chart.html
  examples/misc/legends/legend-numeric-chart.html
  examples/misc/populated-places.html
  src/Layer.js
  src/renderer/viz/expressions/RampGeneric.js
  test/unit/layer.test.js
Labels: 🐛Bug

#1042 Fix width in HighDPI screens
  src/renderer/Renderer.js
Labels: 🐛Bug

#1044 Remove babel-loader from development build
  webpack/webpack.config.js
Labels: 😊 Dev Happiness

#1046 Fallback to value when evaluating in a non-FeatureDependent expression
  CHANGELOG.md
  src/renderer/viz/expressions/base.js
Labels: 🐛Bug

#1063 Change viewportCount() params
  CHANGELOG.md
  docs/guides/deprecated/03-introduction-to-expressions.md
  src/renderer/viz/expressions/aggregation/viewport/ViewportCount.js
  test/unit/renderer/viz/expressions/aggregation/viewportAggregation.test.js
Labels: ✨ Enhancement

#1066 Keep function names in build for production mode
  CHANGELOG.md
  test/unit/renderer/viz/expressions/ramp.test.js
  webpack/webpack.min.config.js
Labels: 🐛Bug

#1075 Set bundle size warning over 425KB
  webpack/webpack.min.config.js
Labels: ✨ Enhancement

#1023 Guides – Visualizing big datasets: aggregations and clustering
  README.md
  docs/guides/01-getting-started.md
  docs/guides/02-using-sources.md
  docs/guides/06-aggregations.md
  docs/guides/09-interactivity-events.md
  examples/editor/css/style.css
  examples/guides/aggregations/step-1.html
  examples/guides/aggregations/step-2.html
  examples/guides/aggregations/step-3.html
  examples/guides/getting-started/step-1.html
  examples/guides/getting-started/step-2.html
  examples/guides/interactivity/step-1.html
  examples/guides/interactivity/step-2.html
  examples/guides/interactivity/step-3.html
  examples/guides/interactivity/step-4.html
  examples/guides/sources/step-1.html
  examples/guides/sources/step-2.html
  examples/guides/sources/step-3.html
  src/Viz.js
  src/renderer/viz/expressions/color/CIELab.js
  src/renderer/viz/expressions/color/hsl.js
  src/renderer/viz/expressions/color/hsv.js
Labels: 📖 Documentation, 🛣 guides

#1100 Fix shader textureIDs with shader cache
  src/Viz.js
  src/renderer/Renderer.js
  src/renderer/shaders/shaderCompiler.js
  test/integration/render/scenarios/regression/shader-cache-bug/reference.png
  test/integration/render/scenarios/regression/shader-cache-bug/scenario.js
Labels: 🐛Bug

#1103 Fix feature `reset()` by ignoring rejected changes
  CHANGELOG.md
  src/Layer.js
  src/Viz.js
  src/renderer/viz/expressions/base.js
  src/renderer/viz/expressions/blend.js
  test/integration/user/test/interactivity.test.js
  test/unit/viz.test.js
Labels: 🐛Bug

#1104 Improve mnmappluto e2e test to test viewportfeatures
  test/acceptance/e2e/mnmappluto/fixture.json
  test/acceptance/e2e/mnmappluto/scenario.js
Labels: tests

#1085 Use interactivity-features in viewportFeatures expression
  CHANGELOG.md
  debug/interactive-based-styling.html
  debug/viewportfeatures-perf.html
  src/interactivity/blendUtils.js
  src/interactivity/feature.js
  src/interactivity/featureVizProperty.js
  src/interactivity/lightweightFeature.js
  src/renderer/RenderLayer.js
  src/renderer/Renderer.js
  src/renderer/viz/expressions/viewportFeatures.js
  test/integration/render/scenarios/viewport/viewportfeatures-viz-properties/reference.png
  test/integration/render/scenarios/viewport/viewportfeatures-viz-properties/scenario.js
  test/integration/user/test/null.test.js
  test/integration/user/test/viewportFeatures.test.js
Labels: 🔀 Expressions, 🙅 do-not-merge
