Repository CartoDB/carto-vl, pull requests merged in 2019-03, with the labels that each got.

#1286 Fix method and add regression test
  CHANGELOG.md
  src/Viz.js
  src/client/windshaft.js
  src/constants/viz.js
  src/interactivity/feature.js
  src/interactivity/lightweightFeature.js
  src/renderer/viz/expressions/ordering.js
  src/renderer/viz/expressions/viewportFeatures.js
  src/renderer/viz/utils/properties.js
  test/integration/user/test/viewportFeatures.test.js
  test/unit/viz.test.js
Labels: 🐛Bug

#1281 Fix global aggregation expressions
  CHANGELOG.md
  src/client/windshaft.js
  src/constants/metadata.js
  src/renderer/Metadata.js
  src/renderer/schema.js
  src/renderer/viz/expressions/CategoryIndex.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterAggregation.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterCount.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterTimeDimension.js
  src/renderer/viz/expressions/aggregation/global/GlobalAggregation.js
  src/renderer/viz/expressions/aggregation/global/GlobalCount.js
  src/renderer/viz/expressions/aggregation/global/GlobalPercentile.js
  src/renderer/viz/expressions/aggregation/global/GlobalSum.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportAvg.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportCount.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportPercentile.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportSum.js
  src/renderer/viz/expressions/basic/number.js
  src/renderer/viz/expressions/basic/property.js
  src/renderer/viz/expressions/basic/variable.js
  src/renderer/viz/expressions/between.js
  src/renderer/viz/expressions/classification/Classifier.js
  src/renderer/viz/expressions/classification/GlobalEqIntervals.js
  src/renderer/viz/expressions/classification/GlobalQuantiles.js
  src/renderer/viz/expressions/classification/GlobalStandardDev.js
  src/renderer/viz/expressions/histogram/ViewportHistogram.js
  src/renderer/viz/expressions/top.js
  src/renderer/viz/expressions/utils.js
  test/integration/user/test/viewportFeatures.test.js
Labels: 🐛Bug, 🔀 Expressions

#1277 Add cluster label examples
  CHANGELOG.md
  debug/point-aggregation-cluster-count.html
  examples/examples.json
  examples/labeling/cluster-labels-average.html
  examples/labeling/cluster-labels-count.html
  examples/labeling/point-labels-aggregate-count.html
  examples/labeling/point-labels-conditional-style.html
  examples/labeling/point-labels-size-zoom.html
  examples/labeling/point-labels.html
  examples/labeling/polygon-labels.html
Labels: 🙅 do-not-merge

#1290 Fix release issues
  CHANGELOG.md
  README.md
  debug/cluster-label-zoom-with-filter.html
  debug/cluster-mode-with-variables.html
  debug/global-quantiles-with-cluster-avg.html
  debug/point-aggregation-cluster-count.html
  debug/viewport-quantiles-with-cluster-count.html
  docs/guides/00-introduction.md
  docs/guides/06-aggregation-and-data-summaries.md
  docs/guides/12-build-custom-charts.md
  docs/guides/Glossary.md
  examples/guides/add-legends/step-8.html
  examples/guides/aggregation-and-data-summaries/step-3.html
  examples/guides/animated-viz/step-5.html
  examples/guides/build-custom-charts/step-1.html
  examples/interactivity/histogram.html
  src/Viz.js
  src/renderer/viz/expressions.js
  src/renderer/viz/expressions/aggregation/cluster/ClusterAggregation.js
  src/renderer/viz/expressions/base.js
  src/renderer/viz/expressions/basic/property.js
  src/renderer/viz/expressions/histogram/Histogram.js
  src/renderer/viz/expressions/histogram/SampleHistogram.js
Labels: 🙅 do-not-merge

#1295 Fix debug examples
  debug/nytaxi.html
  debug/timerange.html
Labels: 🖼️ Examples

#1292 WIP: 1254 animation example enhancements
  examples/animation/add-feature-visibility.html
  examples/animation/animate-and-hold.html
  examples/animation/animate-by-date-range.html
  examples/animation/animate-color-by-date.html
  examples/animation/animate-filtered-features.html
  examples/animation/animate-width.html
  examples/animation/animation-controls.html
  examples/animation/pause.svg
  examples/animation/play.svg
  examples/examples.json
  examples/styling/animation.html
Labels: 🖼️ Examples

#1311 update Classification Variables example to percent + rounded attributes
  examples/advanced/classification-variables.html
Labels: Documentation 📖

#1313 Add more info about browser support and WebGL
  docs/support/03-browser-support.md
Labels: Blocked 🚫
