Repository CartoDB/carto-vl, pull requests merged in 2019-01, with the labels that each got.

#1212 Fix broken links to documentation in README
  README.md
Labels: 🐛Bug, 📖 Documentation

#1213 Add weighted histogram example using a table
  examples/examples.json
  examples/widgets/weighted-histogram.html
Labels: 📖 Documentation, 🖼️ Examples

#1209 Add Labeling examples
  CHANGELOG.md
  debug/centroids.html
  debug/labels-lines-1.html
  debug/labels-points-size-zoom.html
  examples/examples.json
  examples/labeling/point-labels-conditional-style.html
  examples/labeling/point-labels-size-zoom.html
  examples/labeling/point-labels.html
  examples/labeling/polygon-labels.html
  examples/widgets/weighted-histogram.html
  src/renderer/viz/expressions/viewportFeatures.js
Labels: 📖 Documentation, 🙅 do-not-merge

#1233 Fix regression in viewportFeatures
  CHANGELOG.md
  src/renderer/viz/expressions/aggregation/viewport/ViewportAggCalculator.js
  test/integration/user/test/viewportFeatures.test.js
Labels: 🐛Bug

#1235 Fix Content-Type for files deployed to CDN
  CHANGELOG.md
  scripts/cdn/publish.js
Labels: 🐛Bug

#1188 Fix the use of variables in a classification
  .gitignore
  CHANGELOG.md
  examples/advanced/classification-variables.html
  examples/examples.json
  package.json
  src/errors/carto-validation-error.js
  src/renderer/viz/expressions/aggregation/viewport/ViewportHistogram.js
  src/renderer/viz/expressions/base.js
  src/renderer/viz/expressions/classification/Classifier.js
  src/renderer/viz/expressions/classification/ClassifierGLSLHelper.js
  src/renderer/viz/expressions/classification/GlobalEqIntervals.js
  src/renderer/viz/expressions/classification/GlobalQuantiles.js
  src/renderer/viz/expressions/classification/GlobalStandardDev.js
  src/renderer/viz/expressions/classification/ViewportEqIntervals.js
  src/renderer/viz/expressions/classification/ViewportQuantiles.js
  src/renderer/viz/expressions/classification/ViewportStandardDev.js
  src/renderer/viz/expressions/utils.js
  test/integration/user/test/classifications.test.js
  test/unit/errors/carto-validation-error.test.js
  test/unit/renderer/viz/expressions/classification/classifier.test.js
  test/unit/renderer/viz/expressions/ramp.test.js
  test/unit/renderer/viz/expressions/utils.js
  webpack/webpack.min.config.js
Labels: 🐛Bug, 🔀 Expressions
